name: Java CI with Gradle

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: sudo systemctl start postgresql.service
    - run: >
        sudo -u postgres psql
        -c "CREATE DATABASE okapi_modules_test"
        -c "GRANT ALL PRIVILEGES ON DATABASE okapi_modules_test to folio_admin"
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.2
        build-root-directory: service
        arguments: build -Dorg.gradle.jvmargs=-Xmx6G
